In [1]:
!pip install google-colab-shell
from google_colab_shell import getshell
getshell(height=200)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  Created wheel for google-colab-shell: filename=google_colab_shell-0.2-py3-none-any.whl size=4108 sha256=d18e45f299c3c9e3d0d766017707a39f1976c0906b5e85b213c94fe863ade37e
  Stored in directory: /root/.cache/pip/wheels/f9/36/65/95dd4599be065418a9fe1f482674c8e716ce540f3f484681d2
Successfully built google-colab-shell


In [ ]:
#import lib
import numpy as np

In [ ]:
# Khởi tạo numpy

# 1 khởi tạo cơ bản
x = np.array([[5,3],
              [10,2]])
print(f'Khởi tạo mảng numpy: {x}')

# 2 khởi tạo mảng ngẫu nhiên

y = np.random.randn(3, 3)
print(f'Khởi tạo ngẫu nhiên mãng numpy: \n{y}')

# 3 Khởi tạo mảng 0:

z = np.zeros((4,5))
print(f'Khởi tạo mảng 0:\n{z}')


Khởi tạo mảng numpy: [[ 5  3]
 [10  2]]
Khởi tạo ngẫu nhiên mãng numpy: 
[[ 1.61733722 -1.56474535  0.3530431 ]
 [ 1.00250699 -0.09310599  0.20585524]
 [ 1.07375518  0.88397858 -0.49882645]]
Khởi tạo mảng 0:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# Save file numpy 

# Định dạng npy
np.save('/content/sample_data', y)
# Định dạng txt
np.savetxt('/content/file.txt', x)


In [ ]:
# Load file numpyy
# Định dạng npy
y1 = np.load('/content/sample_data.npy')
print(f'Load file numpy định dạng npy:\n{y1}')

# Định dạng txt
x1 = np.loadtxt('/content/file.txt')
print(f'Load file numpy định dạng txt:\n{x1}')



Load file numpy định dạng npy:
[[ 1.61733722 -1.56474535  0.3530431 ]
 [ 1.00250699 -0.09310599  0.20585524]
 [ 1.07375518  0.88397858 -0.49882645]]
Load file numpy định dạng txt:
[[ 5.  3.]
 [10.  2.]]


In [ ]:
# Truy cập numpy

x = np.random.randn(4, 5)
print(f'Khởi tạo mảng ngẫu nhiên:\n{x}')

# Truy cập từng phần tử
print(f'Truy cập phần tử hàng 2 cột 3 của mảng: {x[2,3]}\n')

# Truy cập slice
print(f'Truy cập phần tất cả các phần tử cột 1:\n{x[:,1]}\n')

print(f'Truy cập phần tất cả các phần tử hàng 2:\n{x[2,:]}\n')

print(f'Truy cập phần tử của hàng 2-3:\n{x[2:4,:]}\n')


Khởi tạo mảng ngẫu nhiên:
[[ 1.93159459  0.30791677  0.52710587  1.30191613  1.87882401]
 [-0.43155676  0.20177067  0.64712107  2.01034329  0.31877086]
 [ 0.09760397  0.16150042  1.64427247  0.08844167 -1.01357418]
 [-0.24028041  0.85430731 -1.21819513  0.86245782  0.79359173]]
Truy cập phần tử hàng 2 cột 3 của mảng: 0.08844166840813548

Truy cập phần tất cả các phần tử cột 1:
[0.30791677 0.20177067 0.16150042 0.85430731]

Truy cập phần tất cả các phần tử hàng 2:
[ 0.09760397  0.16150042  1.64427247  0.08844167 -1.01357418]

Truy cập phần tử của hàng 2-3:
[[ 0.09760397  0.16150042  1.64427247  0.08844167 -1.01357418]
 [-0.24028041  0.85430731 -1.21819513  0.86245782  0.79359173]]



In [ ]:
# Thay đổi shape của mảng

x = np.random.randn(3,4)
print(f'Khởi tạo mảng ngẫu nhiên:\n{x}\n')

x1 = x.reshape(6,2)
print(f'Reshape mảng thành 2x6:\n{x1}\n')

#Chuyển vị chiều của mãng

x2 = np.transpose(x)
print(f'Ma trận chuyển vị của x:\n{x2}\n')


Khởi tạo mảng ngẫu nhiên:
[[ 0.72292305 -0.92117409 -0.22616316  1.06090912]
 [-1.09612973 -0.4247498  -0.75632768  0.0406417 ]
 [-0.37755928 -0.91137648 -1.50577494  1.20025923]]

Reshape mảng thành 2x6:
[[ 0.72292305 -0.92117409]
 [-0.22616316  1.06090912]
 [-1.09612973 -0.4247498 ]
 [-0.75632768  0.0406417 ]
 [-0.37755928 -0.91137648]
 [-1.50577494  1.20025923]]

Ma trận chuyển vị của x:
[[ 0.72292305 -1.09612973 -0.37755928]
 [-0.92117409 -0.4247498  -0.91137648]
 [-0.22616316 -0.75632768 -1.50577494]
 [ 1.06090912  0.0406417   1.20025923]]



In [ ]:
# Các hàm min max sum
x = np.random.randn(5,4)
print(x)

min_x = x.min()
print(f'Giá trị nhỏ nhất của x: {min_x}')

max_x = x.max()
print(f'Giá trị lớn nhất của x: {min_x}')

sum_x = x.sum()
print(f'Tổng của array x: {sum_x}')

[[-0.0717673  -0.60295922  1.52418577 -0.31072856]
 [ 1.0819292  -1.03464988  0.41999783 -0.35658112]
 [ 1.10300082  0.51079316 -1.13580527  2.43108113]
 [ 0.66334022  0.17620234  0.27040367  0.78007475]
 [ 1.00582976 -0.77950859  0.44345531  2.60053193]]
Giá trị nhỏ nhất của x: -1.1358052675658448
Giá trị lớn nhất của x: -1.1358052675658448
Tổng của array x: 8.71882596108614
